apiVersion: v1
kind: ServiceAccount
metadata:
  name: kb-indexer-backend-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: pod-listing-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-listing-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: kb-indexer-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: pod-listing-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: job-management-role
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-management-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: kb-indexer-backend-sa
  namespace: default
roleRef:
  kind: Role
  name: job-management-role
  apiGroup: rbac.authorization.k8s.io