apiVersion: v1
kind: Secret
metadata:
  name: kb-indexer-secrets
type: Opaque
data:
  ELASTICSEARCH_USERNAME: PLACEHOLDER
  ELASTICSEARCH_PASSWORD: PLACEHOLDER
  KAGGLE_USERNAME: PLACEHOLDER
  KAGGLE_KEY: PLACEHOLDER
  GH_API_TOKEN: PLACEHOLDER
