apiVersion: v1
kind: Service
metadata:
  labels:
    app: kb-indexer-backend
  name: kb-indexer-backend
spec:
  type: NodePort
  ports:
  - port: 8090
    targetPort: 8090
    protocol: TCP
    name: http
  selector:
    app: kb-indexer-backend
