apiVersion: apps/v1
kind: Deployment
metadata:
  name: kb-indexer-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kb-indexer-backend
  template:
    metadata:
      labels:
        app: kb-indexer-backend
    spec:
      containers:
      - name: kb-indexer-backend
        image: philippsommer27/kb-indexer-backend:latest
        ports:
        - containerPort: 8090
