name: Deploy
on:
  push:
    branches:
      - master
    paths:
      - 'indexconfig/changed_source_files.txt'
  workflow_dispatch:

permissions: 
  actions: read
  id-token: write 
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: philippsommer27/kb-indexer-backend:latest

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          kubelogin-version: 'latest'

      - name: Kubectl tool installer
        uses: Azure/setup-kubectl@v4.0.0
        
      - name: Get AKS context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.CLUSTER_NAME }}
          use-kubelogin: 'true'
      
      - name: Deploy application to AKS
        uses: Azure/k8s-deploy@v4.10.0
        with:
          action: deploy
          manifests: |
             deployments
             
      - name: Clear changed source files list and commit
        run: |
          echo "" > indexconfig/changed_source_files.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add indexconfig/changed_source_files.txt

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Clear changed source files list"
            git push origin master
          fi
          
