name: Build, Push and Deploy Docker image to AKS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions: 
  actions: read
  id-token: write 
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: philippsommer27/kb-indexer-backend:${{ github.ref_name }}

  deploy-to-aks:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - uses: actions/checkout@v3

      - name: Azure login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1

      - name: Get AKS context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          use-kubelogin: 'true'

      - name: Update image version in Kubernetes deployment
        run: |
          sed -i 's|philippsommer27/kb-indexer-backend:latest|philippsommer27/kb-indexer-backend:${{ github.ref_name }}|g' deployments/kb-indexer-backend-deployment.yaml

      - name: Deploy application to AKS
        run: |
          kubectl apply -f deployments/.
        env:
          KUBECONFIG: ${{ github.workspace }}/.kube/config

