name: Update Changed Files List

on:
  push:
    branches:
      - master
    paths:
      - 'indexconfig/sources/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-changed-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Find changed files and update list
      run: |
        git diff --name-only HEAD^ HEAD -- indexconfig/sources/ > indexconfig/changed_source_files.txt

        if [ -s indexconfig/changed_source_files.txt ]; then
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add indexconfig/changed_source_files.txt
          
          FILE=deployments/kb-indexer-backend-deployment.yaml
          UPDATE_VALUE=$(grep -oP 'name: UPDATE\n\s+value: "\K\d+' "$FILE")
          NEW_UPDATE_VALUE=$((UPDATE_VALUE+1))
          sed -i "/name: UPDATE/{n;s/value: \"[^\"]*/value: \"$NEW_UPDATE_VALUE/}" $FILE
          git add $FILE
        
          git commit -m "Update list of changed indexer source files in indexconfig/sources/"
          git push origin master
        else
          echo "No changes in indexconfig/sources/ to update."
        fi
